//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPruebaTecnica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public int IdDireccion { get; set; }
        public string Delegacion { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Estados Estados { get; set; }
    }
}
